name: AhNegaoDiscordBot CI

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: guilhermebkel/ah-negao-discord-bot
        tags: latest

    - name: Run on production
      uses: floms/action-caprover@v1
      with:
        host: '${{ secrets.CAPROVER_HOST }}'
        password: '${{ secrets.CAPROVER_PASSWORD }}'
        app: 'ah-negao-discord-bot'
        image: 'guilhermebkel/ah-negao-discord-bot:latest'
